created component for auth
Anastasiia-Svechnikova/iteam-users pull request #3
Opened 2023-04-03 19:15 UTC by Las04ka

2023-04-04 14:04 UTC, AleaJactaEst commented on angular.json
> +    "analytics": "377e5ac6-d9e6-4bec-89a5-b80db1342564"
do we need this?

2023-04-04 14:05 UTC, AleaJactaEst commented on src/app/app-routing.module.ts
>  import { NgModule } from '@angular/core';
Would prefer lazy loading for auth module

2023-04-04 14:07 UTC, AleaJactaEst commented on src/app/auth/components/auth/auth.component.scss
> +      margin-top: 1vh;
not a fun of 1vh - looks weird

2023-04-04 14:07 UTC, AleaJactaEst commented on src/app/auth/components/auth/auth.component.scss
> +  mat-card {
lets try not to override like that, but instead use classes 

btw: i saw wrapper

2023-04-04 14:09 UTC, AleaJactaEst commented on src/app/auth/components/auth/auth.component.ts
> +    this.isRequesting = store.select(selectRequestingStatus);
can be done on variable init

2023-04-04 14:10 UTC, AleaJactaEst commented on src/app/auth/components/auth/auth.component.ts
> +    if (this.form.valid) {
Kinda not a fun of method called onLogin that doing both login and signup
Lets create abstract class or 2 components

2023-04-04 14:10 UTC, AleaJactaEst commented on src/app/auth/components/auth/auth.component.ts
> +    rememberMe: new FormControl(false),
Do we even use rememberMe?

2023-04-04 14:11 UTC, AleaJactaEst commented on src/app/auth/models/user.ts
> +  user: { id: number };
Is that correct user model :) ?

2023-04-04 14:13 UTC, AleaJactaEst commented on src/app/auth/state/effects.ts
> +  Login$: Observable<Action> = createEffect(() => {
i guess should be login$ isn't?

2023-04-04 14:13 UTC, AleaJactaEst commented on src/app/auth/state/effects.ts
> +            localStorage.setItem(
let's create service to work with local storage

2023-04-04 14:14 UTC, AleaJactaEst commented on src/app/auth/state/effects.ts
> +            this.snackbarService.openSnackBar('Login Success');
'Login Success' - not quite good text - please use from some popular apps, or ask English teacher

2023-04-04 14:15 UTC, AleaJactaEst commented on src/app/auth/state/effects.ts
> +        from(this.authService.login(action.email, action.password)).pipe(
why do we nee from?

2023-04-04 14:15 UTC, AleaJactaEst commented on src/app/auth/state/reducer.ts
> +import {
we cna use import * as LoginAction from..
LoginAction.smth

2023-04-04 14:16 UTC, AleaJactaEst commented on src/app/auth/state/reducer.ts
> +export const selectUserId = createSelector(
selectors should be in separate file

2023-04-05 10:46 UTC, Anastasiia-Svechnikova requested changes

2023-04-05 10:46 UTC, Anastasiia-Svechnikova commented on angular.json
> +    "analytics": "377e5ac6-d9e6-4bec-89a5-b80db1342564"
analytics is probably not neccessary

2023-04-05 10:46 UTC, Anastasiia-Svechnikova commented on src/app/auth/components/auth/auth.component.html
> +          routerLink="/register"
let's better put structural directive first (*ngif)

2023-04-05 10:46 UTC, Anastasiia-Svechnikova commented on src/app/auth/services/auth.service.ts
> +import { environment } from '../../../environments/environment';
It would be better with full path

2023-04-05 10:46 UTC, Anastasiia-Svechnikova commented on src/app/auth/state/effects.ts
> +            this.snackbarService.openSnackBar('Login Successfully');
we can write smth like 'Welcome to I Team! You can start with editing your profile.'

2023-04-05 10:55 UTC, Anastasiia-Svechnikova approved these changes

2023-04-05 12:53 UTC, AleaJactaEst commented on src/app/auth/state/effects.ts
> +          concatMap((loginResponseData: ILoginResponseData) => {
why do we need ** concatMap** here?

2023-04-05 12:54 UTC, AleaJactaEst commented on src/app/auth/state/reducer.ts
> +  on(AuthActions.registerSuccess, (state) => ({
for same function handlere we can combine on methods

2023-04-05 12:55 UTC, AleaJactaEst commented on src/app/auth/state/selectors.ts
> +const selectAuthFeature = createFeatureSelector<IAuthState>('auth');
empty line please

2023-04-05 12:56 UTC, AleaJactaEst commented on src/app/shared/services/local.service.ts
> +  }
empty line please

2023-04-06 08:52 UTC, Anastasiia-Svechnikova approved these changes

2023-04-06 09:26 UTC, AleaJactaEst approved these changes

2023-04-06 09:35 UTC, merged